# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       python3-xmltodict

# >> macros
# << macros
%define int_name xmltodict

Summary:    Makes working with XML feel like you are working with JSON
Version:    0.12.0
Release:    0
Group:      Applications
License:    Apache-2.0
BuildArch:  noarch
URL:        https://pypi.org/project/argcomplete/
Source0:    https://files.pythonhosted.org/packages/x/%{int_name}/%{int_name}-%{version}.tar.gz
Source100:  python3-xmltodict.yaml
BuildRequires:  pkgconfig(python)
BuildRequires:  python3-rpm-macros

%description

xmltodict is a Python module that makes working with XML feel like you are
working with JSON

%if "%{?vendor}" == "chum"
PackageName: argcomplete
Type: console-application
Categories:
 - Library
Custom:
  PackagingRepo: https://github.com/sailfishos-chum/python3-xmltodict
Url:
  Homepage: https://pypi.org/project/argcomplete/
%endif


%prep
%setup -q -n %{int_name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%{py3_build}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%{py3_install}

# >> install post
# << install post

%files
%defattr(-,root,root,-)
# >> files
%license LICENSE
%doc README.md
%{python3_sitelib}/*
# << files
